// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2oHnKd9WmSZY_Pk21aDc2jRXmw1MNA0E',
    appId: '1:573477487412:web:839d8f76b851a867ce9b61',
    messagingSenderId: '573477487412',
    projectId: 'chat-app-8c40e',
    authDomain: 'chat-app-8c40e.firebaseapp.com',
    storageBucket: 'chat-app-8c40e.appspot.com',
    measurementId: 'G-X9QKWM39FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqW9zSM0mrzy-AI5sA59b7QWE4ABUrQ0',
    appId: '1:573477487412:android:25554e15f4b940c9ce9b61',
    messagingSenderId: '573477487412',
    projectId: 'chat-app-8c40e',
    storageBucket: 'chat-app-8c40e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCpbXfVh8wqLNnay0_3af8ogQHce4pBmY',
    appId: '1:573477487412:ios:4c7e9cbe2526ca2ace9b61',
    messagingSenderId: '573477487412',
    projectId: 'chat-app-8c40e',
    storageBucket: 'chat-app-8c40e.appspot.com',
    iosClientId: '573477487412-ruk0phaof8u4n51eenrh2cbr3l57epfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCpbXfVh8wqLNnay0_3af8ogQHce4pBmY',
    appId: '1:573477487412:ios:4c7e9cbe2526ca2ace9b61',
    messagingSenderId: '573477487412',
    projectId: 'chat-app-8c40e',
    storageBucket: 'chat-app-8c40e.appspot.com',
    iosClientId: '573477487412-ruk0phaof8u4n51eenrh2cbr3l57epfh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
